In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [6]:
톨게이트 = pd.read_csv('/Users/hayeon/Downloads/톨게이트 입구 교통량.csv')

In [8]:
확진자 = pd.read_csv('/Users/hayeon/Downloads/TimeProvince.csv')

In [13]:
매출 = pd.read_excel('/Users/hayeon/Downloads/매출.xlsx', header=[0, 1], index_col=[0,1,2])

In [15]:
확진자

date  time          province  confirmed  released  deceased
0     2020.1.20    16             Seoul          0         0         0
1     2020.1.20    16             Busan          0         0         0
2     2020.1.20    16             Daegu          0         0         0
3     2020.1.20    16           Incheon          1         0         0
4     2020.1.20    16           Gwangju          0         0         0
...         ...   ...               ...        ...       ...       ...
2766  2020.6.30     0      Jeollabuk-do         27        21         0
2767  2020.6.30     0      Jeollanam-do         24        19         0
2768  2020.6.30     0  Gyeongsangbuk-do       1389      1328        54
2769  2020.6.30     0  Gyeongsangnam-do        134       128         0
2770  2020.6.30     0           Jeju-do         19        16         0

[2771 rows x 6 columns]

In [31]:
확진자.province.unique()

array(['Seoul', 'Busan', 'Daegu', 'Incheon', 'Gwangju', 'Daejeon',
       'Ulsan', 'Sejong', 'Gyeonggi-do', 'Gangwon-do',
       'Chungcheongbuk-do', 'Chungcheongnam-do', 'Jeollabuk-do',
       'Jeollanam-do', 'Gyeongsangbuk-do', 'Gyeongsangnam-do', 'Jeju-do'],
      dtype=object)

In [33]:
확진자.pivot_table(index=['province','date'],values='confirmed',aggfunc='sum')

confirmed
province date                
Busan    2020.1.20          0
         2020.1.21          0
         2020.1.22          0
         2020.1.23          0
         2020.1.24          0
...                       ...
Ulsan    2020.6.5          52
         2020.6.6          52
         2020.6.7          53
         2020.6.8          53
         2020.6.9          53

[2771 rows x 1 columns]

In [70]:
전국일자매출합계 = 매출.sum(axis=1)

In [51]:
지역명 = ['전국','서울특별시','부산광역시','대구광역시','인천광역시','광주광역시',
      '대전광역시','울산광역시','세종특별자치시','경기도','강원도','충청북도','충청남도','전라북도','전라남도',
      '경상북도','경상남도','제주특별자치도']

In [61]:
매출.전국.sum(axis=1)

구분         
2019  1  1     1.244484e+11
         2     9.010527e+10
         3     9.170426e+10
         4     1.039682e+11
         5     1.379349e+11
                   ...     
2021  7  14    6.324676e+10
         15    6.559258e+10
         16    6.937852e+10
         17    9.288544e+10
         18    7.374922e+10
Length: 930, dtype: float64

In [79]:
매출

전국                                                \
                   총소비         숙박업        여행업        대중교통        렌터카   
구분                                                                     
2019 1 1   62224211777  2558825216    4968700  1924099650   18484650   
       2   45052634245  1310859797  497752491  2086178560   20474430   
       3   45852131106  1183359462  458739351  1992871610   25622490   
       4   51984099037  1260500864  432180223  2145175680   21801880   
       5   68967443731  2666735728    9644100  1909402850   16523792   
...                ...         ...        ...         ...        ...   
2021 7 14  31623382400   809747146    2048000  1077868690   48080693   
       15  32796287921   755331537    6249000  1090511050  988291713   
       16  34689259114   708896211    2769000  1232399820   44375995   
       17  46442721082  1187237741    5850700  1085949940   48634951   
       18  36874612229   869045759    8672290   184978630   37100545   

                                                                         ...  \
                  항공사           카지노       레저스포츠         면세점       문화서비스  ...   
구분                                                                       ...   
2019 1 1    738970484  1.266470e+09  2115910673  4844465840  1487135187  ...   
       2   1853743070  1.562090e+09  1993970278  4074518789   567717534  ...   
       3   1729865090  1.232550e+09  1698205084  4170845081   559614568  ...   
       4   2046498007  1.762180e+09  1829628490  4123577829   652714552  ...   
       5    823053064  1.689120e+09  2603613532  4058066162  1176269891  ...   
...               ...           ...         ...         ...         ...  ...   
2021 7 14   460779488  5.530000e+06  3398587107   273577872   247313082  ...   
       15   471697336           NaN  3385253617   263872658   144474160  ...   
       16   398677108  5.750000e+07  3316208980    52986763   160890033  ...   
       17   293946214  1.400000e+07  4009992231    13123695   307348360  ...   
       18   223367340  8.450000e+07  3917553255    46618120   199534270  ...   

             제주특별자치도                                                           \
                 여행업       렌터카          항공사      레저스포츠          면세점     문화서비스   
구분                                                                              
2019 1 1     61000.0  18050750   58928982.0   61933157  481877021.0  33116980   
       2    467860.0  17536830  145949489.0   41725935  387521815.0  15543410   
       3    383800.0  25622490  144124856.0   37519667  319779565.0  13185005   
       4    840940.0  17332580  169192413.0   42233023  302662373.0  14356740   
       5    587500.0  13828192   67545145.0   59147253  386995488.0  21968790   
...              ...       ...          ...        ...          ...       ...   
2021 7 14   209800.0  45657422   42181100.0  106376570  227289170.0  15611350   
       15  4342300.0  38311810   42503700.0  103651940  221494510.0  14020500   
       16   654200.0  42153045   38078100.0   86587450    1267640.0  16020900   
       17  1207700.0  47662051   36817700.0  120586270     830620.0  19113900   
       18  2452890.0  36701545          NaN  107776953          NaN  24107600   

                                               
          쇼핑(면세점 제외)        식음료      대중교통 카지노  
구분                                             
2019 1 1   106313420  554254221       NaN NaN  
       2    74976750  441263408  110000.0 NaN  
       3    69471872  448673705       NaN NaN  
       4    61056660  481995188       NaN NaN  
       5    72216890  556552443  420000.0 NaN  
...              ...        ...       ...  ..  
2021 7 14   67080680  701792203       NaN NaN  
       15   70154270  688867685       NaN NaN  
       16   64902840  708434562   98000.0 NaN  
       17   75842308  790485030       NaN NaN  
       18   69244110  750081992  164000.0 NaN  

[930 rows x 184 columns]

In [84]:
li = []
for name in 지역명:
    a = name,매출[name].총소비
    print(a)
    print()

('전국', 구분         
2019  1  1     62224211777
         2     45052634245
         3     45852131106
         4     51984099037
         5     68967443731
                  ...     
2021  7  14    31623382400
         15    32796287921
         16    34689259114
         17    46442721082
         18    36874612229
Name: 총소비, Length: 930, dtype: int64)

('서울특별시', 구분         
2019  1  1     18325049873
         2     17598098778
         3     18390219882
         4     20703215962
         5     22762898246
                  ...     
2021  7  14     8381639587
         15     8208174651
         16     8839825686
         17     9704929744
         18     6966148543
Name: 총소비, Length: 930, dtype: int64)

('부산광역시', 구분         
2019  1  1     6225070964
         2     4423856448
         3     4235021122
         4     4643037987
         5     6514295261
                  ...    
2021  7  14    2830894588
         15    2854809241
         16    3152784272
         17    4098706150
     

In [73]:
코로나 = pd.read_csv('/Users/hayeon/Downloads/corona.csv')

In [104]:
코로나.pivot_table(index=['province','date'], values='new_confirmed', aggfunc='sum')

new_confirmed
province date                    
Busan    2020.1.20              0
         2020.1.21              0
         2020.1.22              0
         2020.1.23              0
         2020.1.24              0
...                           ...
Ulsan    2021.3.5               3
         2021.3.6               4
         2021.3.7               2
         2021.3.8               3
         2021.3.9              11

[7429 rows x 1 columns]

In [92]:
# 2020.1.20 ~ 21.3.31
기간지정 = 매출.loc[(2020,1,20):(2021,3,31)]

In [116]:
tes = 기간지정.T

In [170]:
tes.loc['전국','총소비']

구분         
2020  1  20    4.250439e+10
         21    4.487312e+10
         22    4.691468e+10
         23    5.747070e+10
         24    5.850656e+10
                   ...     
2021  3  27    5.171519e+10
         28    4.132630e+10
         29    3.096465e+10
         30    3.331770e+10
         31    3.621798e+10
Name: (전국, 총소비), Length: 437, dtype: float64

In [218]:
기간확진자 = 코로나.groupby('date').sum().new_confirmed

In [219]:
기간전국매출 = 기간지정.전국.총소비

In [220]:
corr = np.corrcoef(기간확진자, 기간전국매출)
print(corr)

[[ 1.         -0.13975997]
 [-0.13975997  1.        ]]


In [229]:
부산확진 = 코로나[코로나.province=='Busan'].new_confirmed

In [230]:
부산매출 = 기간지정.부산광역시.총소비

In [231]:
corr = np.corrcoef(부산확진, 부산매출)
print(corr)

[[ 1.         -0.34187527]
 [-0.34187527  1.        ]]


> **부산확진자가 늘어나면 부산 매출이 감소하는 약한 음의 상관관계가 있다**

In [233]:
코로나.province.unique()

array(['Seoul', 'Busan', 'Daegu', 'Incheon', 'Gwangju', 'Daejeon',
       'Ulsan', 'Sejong', 'Gyeonggi-do', 'Gangwon-do',
       'Chungcheongbuk-do', 'Chungcheongnam-do', 'Jeollabuk-do',
       'Jeollanam-do', 'Gyeongsangbuk-do', 'Gyeongsangnam-do', 'Jeju-do',
       'Jeju'], dtype=object)

---
> **강원도 확진-매출 상관관계**

In [234]:
강원도확진 = 코로나[코로나.province=='Gangwon-do'].new_confirmed
강원도매출 = 기간지정.강원도.총소비

In [235]:
corr = np.corrcoef(강원도확진, 강원도매출)
print(corr)

[[ 1.         -0.23355179]
 [-0.23355179  1.        ]]


In [241]:
코로나[코로나.province=='Daegu'].new_confirmed

2        0
19       0
36       0
53       0
70       0
        ..
7358    23
7375    10
7391    10
7408    12
7424    15
Name: new_confirmed, Length: 437, dtype: int64

# ============================

In [265]:
for name in new_지역 : 
      for name2 in 지역명:
        corona = 코로나[코로나.province==name].new_confirmed
    #print(name, corona)
          
        sales = 기간지정[name2].총소비

        corr = np.corrcoef(corona, sales)
        print(name, name2)
        print(corr)
        corona = pd.Series()
        sales = pd.Series()
        print('====================')

Seoul 전국
[[ 1.         -0.39247564]
 [-0.39247564  1.        ]]
Seoul 서울특별시
[[ 1.         -0.55154155]
 [-0.55154155  1.        ]]
Seoul 부산광역시
[[ 1.         -0.35301424]
 [-0.35301424  1.        ]]
Seoul 대구광역시
[[ 1.       -0.075665]
 [-0.075665  1.      ]]
Seoul 인천광역시
[[ 1.         -0.39538125]
 [-0.39538125  1.        ]]
Seoul 광주광역시
[[ 1.         -0.31225998]
 [-0.31225998  1.        ]]
Seoul 대전광역시
[[ 1.         -0.39138383]
 [-0.39138383  1.        ]]
Seoul 울산광역시
[[ 1.         -0.29497668]
 [-0.29497668  1.        ]]
Seoul 세종특별자치시
[[ 1.         -0.36109933]
 [-0.36109933  1.        ]]
Seoul 경기도
[[ 1.         -0.32957685]
 [-0.32957685  1.        ]]
Seoul 강원도
[[ 1.       -0.249804]
 [-0.249804  1.      ]]
Seoul 충청북도
[[ 1.         -0.36677705]
 [-0.36677705  1.        ]]
Seoul 충청남도
[[ 1.        -0.2523904]
 [-0.2523904  1.       ]]
Seoul 전라북도
[[ 1.         -0.28143073]
 [-0.28143073  1.        ]]
Seoul 전라남도
[[ 1.         -0.24325604]
 [-0.24325604  1.        ]]
Seoul 경상북도
[[ 1.        

<ipython-input-265-1bc6162a5ba3>:11: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  corona = pd.Series()
<ipython-input-265-1bc6162a5ba3>:12: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  sales = pd.Series()


 강원도
[[ 1.         -0.13772136]
 [-0.13772136  1.        ]]
Daejeon 충청북도
[[ 1.         -0.19006074]
 [-0.19006074  1.        ]]
Daejeon 충청남도
[[ 1.         -0.15136289]
 [-0.15136289  1.        ]]
Daejeon 전라북도
[[ 1.         -0.18239459]
 [-0.18239459  1.        ]]
Daejeon 전라남도
[[ 1.         -0.15777955]
 [-0.15777955  1.        ]]
Daejeon 경상북도
[[ 1.         -0.11556898]
 [-0.11556898  1.        ]]
Daejeon 경상남도
[[ 1.         -0.15402633]
 [-0.15402633  1.        ]]
Daejeon 제주특별자치도
[[ 1.         -0.11041241]
 [-0.11041241  1.        ]]
Ulsan 전국
[[ 1.         -0.31342078]
 [-0.31342078  1.        ]]
Ulsan 서울특별시
[[ 1.         -0.39283735]
 [-0.39283735  1.        ]]
Ulsan 부산광역시
[[ 1.         -0.27943931]
 [-0.27943931  1.        ]]
Ulsan 대구광역시
[[ 1.         -0.11821257]
 [-0.11821257  1.        ]]
Ulsan 인천광역시
[[ 1.         -0.27987673]
 [-0.27987673  1.        ]]
Ulsan 광주광역시
[[ 1.        -0.2323161]
 [-0.2323161  1.       ]]
Ulsan 대전광역시
[[ 1.         -0.30502458]
 [-0.30502458  1.        ]]

Jeollabuk-do 대구광역시
[[ 1.         -0.04316755]
 [-0.04316755  1.        ]]
Jeollabuk-do 인천광역시
[[ 1.         -0.28696437]
 [-0.28696437  1.        ]]
Jeollabuk-do 광주광역시
[[ 1.         -0.19076076]
 [-0.19076076  1.        ]]
Jeollabuk-do 대전광역시
[[ 1.         -0.26663081]
 [-0.26663081  1.        ]]
Jeollabuk-do 울산광역시
[[ 1.         -0.20250352]
 [-0.20250352  1.        ]]
Jeollabuk-do 세종특별자치시
[[ 1.         -0.21868846]
 [-0.21868846  1.        ]]
Jeollabuk-do 경기도
[[ 1.         -0.24106452]
 [-0.24106452  1.        ]]
Jeollabuk-do 강원도
[[ 1.         -0.21410936]
 [-0.21410936  1.        ]]
Jeollabuk-do 충청북도
[[ 1.         -0.25420942]
 [-0.25420942  1.        ]]
Jeollabuk-do 충청남도
[[ 1.         -0.18806359]
 [-0.18806359  1.        ]]
Jeollabuk-do 전라북도
[[ 1.         -0.20824324]
 [-0.20824324  1.        ]]
Jeollabuk-do 전라남도
[[ 1.         -0.18971553]
 [-0.18971553  1.        ]]
Jeollabuk-do 경상북도
[[ 1.         -0.12817364]
 [-0.12817364  1.        ]]
Jeollabuk-do 경상남도
[[ 1.         -0.19217692]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 101 and the array at index 1 has size 437

In [249]:
코로나.province.unique()

array(['Seoul', 'Busan', 'Daegu', 'Incheon', 'Gwangju', 'Daejeon',
       'Ulsan', 'Sejong', 'Gyeonggi-do', 'Gangwon-do',
       'Chungcheongbuk-do', 'Chungcheongnam-do', 'Jeollabuk-do',
       'Jeollanam-do', 'Gyeongsangbuk-do', 'Gyeongsangnam-do', 'Jeju-do',
       'Jeju'], dtype=object)

In [250]:
지역명

['전국',
 '서울특별시',
 '부산광역시',
 '대구광역시',
 '인천광역시',
 '광주광역시',
 '대전광역시',
 '울산광역시',
 '세종특별자치시',
 '경기도',
 '강원도',
 '충청북도',
 '충청남도',
 '전라북도',
 '전라남도',
 '경상북도',
 '경상남도',
 '제주특별자치도']

In [251]:
new_지역 = ['Seoul', 'Busan', 'Daegu', 'Incheon', 'Gwangju', 'Daejeon',
       'Ulsan', 'Sejong', 'Gyeonggi-do', 'Gangwon-do',
       'Chungcheongbuk-do', 'Chungcheongnam-do', 'Jeollabuk-do',
       'Jeollanam-do', 'Gyeongsangbuk-do', 'Gyeongsangnam-do', 'Jeju-do',
       'Jeju']